Month 10/step 1
Klyuch97/react-stellar-burger pull request #8
Opened 2023-10-25 19:48 UTC by Klyuch97

2023-10-25 20:23 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Сильные стороны работы:
- Использовали union типы
- Хорошая типизация компонентов
- Не использовали ts-ignore

Необходимо исправить:
- В проекте много `any` - они сводят типизацию на нет. От большинства можно избавиться

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-10-25 20:23 UTC, andryxxa93 commented on src/components/burger-constructor/ingridients-additives/ingridients-additives.tsx
> +        hover: (item:any, monitor) => {
**Можно лучше**
Тут от any можно избавиться - подсмотреть как можно в документации к библиотеке `react-dnd` в разделе examples.

2023-10-26 07:32 UTC, Klyuch97 commented
не понимаю как убрать any в export const useDispatch = () => dispatchHook<AppDispatch | AppThunk | any>();
вылазят ошибки, и от каких  any еще следует избавиться

2023-10-26 17:50 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-12-11 06:18 UTC, merged